[package]
name = "backend_gcd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio={version="1.14.0", features=["full"]}
actix-web="4.1"
serde={version="1.0" ,features=["derive"]}
image="0.25.0"
rand="0.8"
num="0.4"
crossbeam="0.8"
